### PR TITLE
Reword error messages to avoid the use of "identifier",

### PR DESCRIPTION
**Pull request by blerner**
while also not conflating mutable and immutable "variables"..

### CODE REVIEW

**Comment by blerner** [comment]
This PR should fix #1716 .

**Review by schanzer — COMMENTED** [review]
@blerner overall this feels like a small-but-meaningful improvement for Bootstrap's use-cases. And after our call today, if we can accomplish this without degrading things for Pyret's other audiences I'd say that's a big win.

Question: would it be possible to offer a suggestion, at least if the srcloc comes from the Interactions Area? Something like "have you Run the program recently?"

**Comment by blerner** [comment]
I'm torn on that suggestion -- the downsides of it being wrong (and causing the student to lose whatever experimentation in the REPL they had) seem much worse than the upside of getting it right ("wow how did you guess I hadn't done that in a while?!")

**Comment by schanzer** [comment]
With Pyret's REPL history in place, this doesn't seem like such a destructive thing to me, but I won't fight you on this. :)

**Comment by schanzer** [comment]
@jpolitz the wording change Ben makes here ("name" instead of "identifier") has the blessing of the entire curriculum team. Can this be merged in the next few weeks?

**Pull request merged**
