### PR TITLE
+cases optimization +convert concat-lists to tail position

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by awstlaur** [comment]
I like seeing the word "optimization," but I imagine the proposed diff would have to be re-worked.

**Comment by sorawee** [comment]
As I understand, @jpolitz 's new module system partially optimizes case dispatching already, so this PR is no longer irrelevant?

**Comment by blerner** [comment]
No, @sorawee, it's still relevant.  Could you rebase it on memo-jsast please?  I'll merge it once you have.

**Comment by sorawee** [comment]
Yup. Will do that soon.

**Comment by blerner** [comment]
pine @sorawee : could you now rebase this onto _horizon_, since memo-jsast has merged already?

**Comment by sorawee** [comment]
Submit this as a new PR at #1055, so closing this.

**Pull request closed without merging**
