### PR TITLE
Benchmarking tools: v2.0.0

### PR DESCRIPTION
**Pull request by awstlaur**
Big overhaul of benchmarking tools. Major changes include using version 2.0.0 of benchmark.js, adding an "all" field to auto reports, redoing how benchmarking the evaluation was done, and letting the benchmark library have more time in order to get to a lower margin of error. Also, the test cases now run with the same configuration as the rest of the tests in the code base.

Note the changes to Makefile and package.json.

I have made updates to the [visualization website](http://cs.brown.edu/~awstlaur/pyret-benchmark-visualization/) in parallel.

### CODE REVIEW

**Comment by sorawee** [comment]
```
~/pyret-lang-working/tools/benchmark$ node measure-program.js auto-report-programs/recursion-tail-call.arr
CURRENT BENCHMARK: auto-report-programs/recursion-tail-call.arr
Ensuring program runs successfully...
...done.
parse x 142 ops/sec +/- 1.53% (737 runs sampled)
load x 5.48 ops/sec +/- 3.15% (325 runs sampled)
eval x 4.01 ops/sec +/- 2.06% (239 runs sampled)
all x 2.38 ops/sec +/- 1.39% (145 runs sampled)
~/pyret-lang-working/node_modules/benchmark/benchmark.js:1855
      result[index] = callback.call(thisArg, value, index, array);
                               ^
TypeError: undefined is not a function
    at ~/pyret-lang-working/node_modules/benchmark/benchmark.js:1855:32
    at ~/pyret-lang-working/node_modules/benchmark/benchmark.js:1888:58
    at forEach (~/pyret-lang-working/node_modules/benchmark/benchmark.js:1527:11)
    at reduce (~/pyret-lang-working/node_modules/benchmark/benchmark.js:1887:5)
    at map (~/pyret-lang-working/node_modules/benchmark/benchmark.js:1854:12)
    at Suite.map (~/pyret-lang-working/node_modules/benchmark/benchmark.js:1100:17)
    at Suite.<anonymous> (~/pyret-lang-working/tools/benchmark/benchmark-pyret.js:207:72)
    at ~/pyret-lang-working/node_modules/benchmark/benchmark.js:2108:38
    at forEach (~/pyret-lang-working/node_modules/benchmark/benchmark.js:1527:11)
    at Suite.emit (~/pyret-lang-working/node_modules/benchmark/benchmark.js:2107:7)
```

**Comment by sorawee** [comment]
This version is much better, by the way. I always get +/- 170% from the previous version...

**Comment by awstlaur** [comment]
@sorawee, did you reinstall benchmark.js ? The version bumped to 2.0.0. 

If so, what version of node did you use to run it?

**Comment by sorawee** [comment]
Ahh, I didn't. Good catch.

**Pull request merged**
