### PR TITLE
Compliler can now handle absolute as well as relative paths (issue #969)

### PR DESCRIPTION
**Pull request by SethPoulsen**
I didn't rebuild phase0 because I didn't think this constituted a "major change" that would merit a whole new bootstrap.

### CODE REVIEW

**Comment by SethPoulsen** [comment]
For what its worth, on my machine all tests pass and phaseB and phaseC build identically. I assume the failing build is due to some sort of authentication issue.

**Comment by jpolitz** [comment]
Thanks for making this change! Would you mind opening a new PR that targets the `horizon` branch instead of `master`? We generally flow new changes through that branch, sorry that isn't clearer. I also made a change to the `.travis.yml` on `horizon` just now that should skip the credentials-requiring part of the build, allowing this to cleanly pass.

Separately, @blerner there's a design decision here – should we have the file locator be able to do relative paths? I think it's OK (it's more annoying to not have available) but we have a choice to lock things down to relative paths or not here, and it's a decision we're making either way.

**Comment by SethPoulsen** [comment]
@jpolitz Sounds good. I knew that actually, I targeted `master` by mistake. It will take me a bit because I accidentally branched from `master` in the first place, but I should be able to sort it out soon.

**Comment by blerner** [comment]
I think we do want to allow relative paths, but I think we need to be careful, because it'll make things a lot harder to abstract away from the machine-on-which-the-jarr-was-made's file system.  We had talked a while ago about canonicalizing paths in locators to be relative to the build directory, so that `/my/private/filesystem/organization/pyret-project/src` just becomes `src/`.  If we allow files outside that space, we'll need to be a bit more precise about what that normalization means.

**Comment by SethPoulsen** [comment]
If you want everything in reference to the build directory internally, rather than allowing absolute and relative paths, we could just change the `get-real-path` function I created to convert all absolute paths to relative paths starting at the build directory.

**Pull request closed without merging**
