### PR TITLE
Add annotation for table-from-raw-array(), checking arg is indeed a raw array of rows 

### PR DESCRIPTION
**Pull request by ds26gte**
addresses issue #1758

### CODE REVIEW

**Comment by jpolitz** [comment]
A few tests here would help: https://github.com/brownplt/pyret-lang/blob/horizon/tests/pyret/tests/test-tables.arr#L653

You can see some similar style of tests (for dynamic annotation-checking errors in the table library) here: https://github.com/brownplt/pyret-lang/blob/horizon/tests/pyret/tests/test-tables.arr#L507

**Comment by ds26gte** [comment]
Just one test added. Is there more variety needed in this situation?

**Comment by blerner** [comment]
This looks like it merely tests that the argument is a raw array; it doesn't check that the elements are checked as well.

**Comment by ds26gte** [comment]
@blerner, are you referring to having a test case that checks that something like 
```
  [table-from-rows:
    [raw-row: 5, {"B"; 7}, {"C"; 8}],
    [raw-row: {"A"; 1}, {"B"; 2}, {"C"; 3}]]
```
fails?

Or are you saying that the predicate I used in `tables.arr` is merely checking that the argument is a raw-array of raw-rows, but doesn't further check that each raw-row contains only key-value pairs?  The latter is already taken care of by the existing code once the initial check that it's all raw-rows passes.

I can add the test case above to `test-tables.arr`, but you already have in place a more stringent test, i.e., that the key-value pairs have matching keys in the correct order across all the rows. This new test is pretty basic in comparison.

**Comment by blerner** [comment]
I'm saying you have no test case that fails in the `is-row` check of https://github.com/brownplt/pyret-lang/pull/1759/files#diff-9e511711584173e90288d8fe12034bea103c3de800fdd9b50fcf38dd0479b273R92.  So `[table-from-rows: 1, [raw-row: ...], false, [raw-row: ...], "a string that's definitely not a row", ...]`.

Additionally, implementing the annotation in Pyret as a refinement will give you a lousier error message than if you implemented it as an annotation in JS, as we do in the image library, as I pointed you towards in the original issue.

**Pull request merged**
