### PR TITLE
Use SVG asset for CI build status

### PR DESCRIPTION
**Pull request by liangricha**

### CODE REVIEW

**Comment by liangricha** [comment]
Hmm I can't seem to download Racket locally either (getting a 403 as well). Out of curiosity, which tests depend on Racket?

**Comment by liangricha** [comment]
The Racket DL issue seems to be resolved, and triggering a rebuild resulted in passing tests.

**Comment by jpolitz** [comment]
Cool, thanks!

FWIW, Racket is used to build the documentation, which use https://docs.racket-lang.org/scribble/.

Happy to merge this; I like SVG.  Is there a particular reason to prefer it in this case?

**Comment by liangricha** [comment]
The image will look nice in all screen resolutions :stuck_out_tongue_winking_eye: (it's currently kinda blurry on my MBP 15-inch retina). Travis CI seems to also be using SVG icons instead of PNGs for their status images. Not a huge deal in particular.

**Pull request merged**
