### PR TITLE
Switched over to immutable-js string-dict implementation

### PR DESCRIPTION
**Pull request by mkolosick**
Uses the optimized version of string-dict for immutable string dicts.

### CODE REVIEW

**Comment by jpolitz** [comment]
From the failed build:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

I wonder if this implementation has some bad performance characteristics on existing code?

**Comment by mkolosick** [comment]
I will look into that.

**Comment by jpolitz** [comment]
It actually looks like it might be taking longer on type-check tests, which is really odd (though I actually don't know).

Those lines of output at the bottom print during the general language/lib tests, and type tests run after.  Compare to this build output, where the type tests are enumerated afterwards:

https://travis-ci.org/brownplt/pyret-lang/builds/170315903

**Comment by mkolosick** [comment]
There appears to be a memory leak. I will continue to investigate.

**Pull request closed without merging**
