### PR TITLE
Add support of a trailing comma in record annotation and tests

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by sorawee** [comment]
Oh shoot, just realized this allows `{ , }`. Will fix in the next commit.

**Comment by blerner** [comment]
This broke parse-pyret.js -- look at the travis results, and try rerunning make test on your own.

**Comment by sorawee** [comment]
Ughh. It passes `make parse-test` locally on my computer...

**Comment by jpolitz** [comment]
This LGTM with the fixes..  @blerner, any objections?

**Comment by blerner** [comment]
Nope, I'm good with it

**Pull request merged**
